Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'features/**/*'
    - 'lib/simply_record/*'
    - 'lib/tasks/*'
    - 'script/*'
    - 'vendor/**/*'
    - 'bin/spring'


Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false